In [1]:
import pandas as pd

In [2]:
pokemon = pd.read_csv('Pokemon.csv')
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [3]:
pokemon.set_index(['Name', 'Type 1'], inplace=True)
pokemon

,,#,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,Type 1,,,,,,,,,,,
Bulbasaur,Grass,1,Poison,318,45,49,49,65,65,45,1,False
Ivysaur,Grass,2,Poison,405,60,62,63,80,80,60,1,False
Venusaur,Grass,3,Poison,525,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,Grass,3,Poison,625,80,100,123,122,120,80,1,False
Charmander,Fire,4,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
Diancie,Rock,719,Fairy,600,50,100,150,100,150,50,6,True
DiancieMega Diancie,Rock,719,Fairy,700,50,160,110,160,110,110,6,True
HoopaHoopa Confined,Psychic,720,Ghost,600,80,110,60,150,130,70,6,True
HoopaHoopa Unbound,Psychic,720,Dark,680,80,160,60,170,130,80,6,True
Volcanion,Fire,721,Water,600,80,110,120,130,90,70,6,True

In [4]:
pokemon.index

MultiIndex([(                'Bulbasaur',   'Grass'),
            (                  'Ivysaur',   'Grass'),
            (                 'Venusaur',   'Grass'),
            (    'VenusaurMega Venusaur',   'Grass'),
            (               'Charmander',    'Fire'),
            (               'Charmeleon',    'Fire'),
            (                'Charizard',    'Fire'),
            ('CharizardMega Charizard X',    'Fire'),
            ('CharizardMega Charizard Y',    'Fire'),
            (                 'Squirtle',   'Water'),
            ...
            (                   'Noibat',  'Flying'),
            (                  'Noivern',  'Flying'),
            (                  'Xerneas',   'Fairy'),
            (                  'Yveltal',    'Dark'),
            (         'Zygarde50% Forme',  'Dragon'),
            (                  'Diancie',    'Rock'),
            (      'DiancieMega Diancie',    'Rock'),
            (      'HoopaHoopa Confined', 'Psychic'),
            (       'HoopaHoopa Unbound', 'Psychic'),
            (                'Volcanion',    'Fire')],
           names=['Name', 'Type 1'], length=800)

In [5]:
pokemon.index.get_level_values(1)

Index(['Grass', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Fire',
       'Fire', 'Water',
       ...
       'Flying', 'Flying', 'Fairy', 'Dark', 'Dragon', 'Rock', 'Rock',
       'Psychic', 'Psychic', 'Fire'],
      dtype='object', name='Type 1', length=800)

In [6]:
pokemons = pokemon.swaplevel()
pokemons

                                 #  Type 2  Total  HP  Attack  Defense  \
Type 1  Name
Grass   Bulbasaur                1  Poison    318  45      49       49
        Ivysaur                  2  Poison    405  60      62       63
        Venusaur                 3  Poison    525  80      82       83
        VenusaurMega Venusaur    3  Poison    625  80     100      123
Fire    Charmander               4     NaN    309  39      52       43
...                            ...     ...    ...  ..     ...      ...
Rock    Diancie                719   Fairy    600  50     100      150
        DiancieMega Diancie    719   Fairy    700  50     160      110
Psychic HoopaHoopa Confined    720   Ghost    600  80     110       60
        HoopaHoopa Unbound     720    Dark    680  80     160       60
Fire    Volcanion              721   Water    600  80     110      120

                               Sp. Atk  Sp. Def  Speed  Generation  Legendary
Type 1  Name
Grass   Bulbasaur                   65       65     45           1      False
        Ivysaur                     80       80     60           1      False
        Venusaur                   100      100     80           1      False
        VenusaurMega Venusaur      122      120     80           1      False
Fire    Charmander                  60       50     65           1      False
...                                ...      ...    ...         ...        ...
Rock    Diancie                    100      150     50           6       True
        DiancieMega Diancie        160      110    110           6       True
Psychic HoopaHoopa Confined        150      130     70           6       True
        HoopaHoopa Unbound         170      130     80           6       True
Fire    Volcanion                  130       90     70           6       True

[800 rows x 11 columns]

In [8]:
pokemons.sort_values('Type 1')

                   #    Type 2  Total   HP  Attack  Defense  Sp. Atk  Sp. Def  \
Type 1 Name
Bug    Sewaddle  540     Grass    310   45      53       70       40       60
       Pinsir    127       NaN    500   65     125      100       55       70
       Burmy     412       NaN    224   40      29       45       29       45
       Scyther   123    Flying    500   70     110       80       55       80
       Joltik    595  Electric    319   50      47       50       57       50
...              ...       ...    ...  ...     ...      ...      ...      ...
Water  Totodile  158       NaN    314   50      65       64       44       48
       Basculin  550       NaN    460   70      92       65       80       55
       Vaporeon  134       NaN    525  130      65       60      110       95
       Panpour   515       NaN    316   50      53       48       53       48
       Chinchou  170  Electric    330   75      38       38       56       56

                 Speed  Generation  Legendary
Type 1 Name
Bug    Sewaddle     42           5      False
       Pinsir       85           1      False
       Burmy        36           4      False
       Scyther     105           1      False
       Joltik       65           5      False
...                ...         ...        ...
Water  Totodile     43           2      False
       Basculin     98           5      False
       Vaporeon     65           1      False
       Panpour      64           5      False
       Chinchou     67           2      False

[800 rows x 11 columns]

In [9]:
pokemon = pd.read_csv('Pokemon.csv', index_col=['Type 1', 'Name'])
pokemon

                                 #  Type 2  Total  HP  Attack  Defense  \
Type 1  Name
Grass   Bulbasaur                1  Poison    318  45      49       49
        Ivysaur                  2  Poison    405  60      62       63
        Venusaur                 3  Poison    525  80      82       83
        VenusaurMega Venusaur    3  Poison    625  80     100      123
Fire    Charmander               4     NaN    309  39      52       43
...                            ...     ...    ...  ..     ...      ...
Rock    Diancie                719   Fairy    600  50     100      150
        DiancieMega Diancie    719   Fairy    700  50     160      110
Psychic HoopaHoopa Confined    720   Ghost    600  80     110       60
        HoopaHoopa Unbound     720    Dark    680  80     160       60
Fire    Volcanion              721   Water    600  80     110      120

                               Sp. Atk  Sp. Def  Speed  Generation  Legendary
Type 1  Name
Grass   Bulbasaur                   65       65     45           1      False
        Ivysaur                     80       80     60           1      False
        Venusaur                   100      100     80           1      False
        VenusaurMega Venusaur      122      120     80           1      False
Fire    Charmander                  60       50     65           1      False
...                                ...      ...    ...         ...        ...
Rock    Diancie                    100      150     50           6       True
        DiancieMega Diancie        160      110    110           6       True
Psychic HoopaHoopa Confined        150      130     70           6       True
        HoopaHoopa Unbound         170      130     80           6       True
Fire    Volcanion                  130       90     70           6       True

[800 rows x 11 columns]

In [13]:
pokemon.loc['Grass']

,#,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,
Bulbasaur,1,Poison,318,45,49,49,65,65,45,1,False
Ivysaur,2,Poison,405,60,62,63,80,80,60,1,False
Venusaur,3,Poison,525,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,3,Poison,625,80,100,123,122,120,80,1,False
Oddish,43,Poison,320,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...
Chespin,650,NaN,313,56,61,65,48,45,38,6,False
Quilladin,651,NaN,405,61,78,95,56,58,57,6,False
Chesnaught,652,Fighting,530,88,107,122,74,75,64,6,False
Skiddo,672,NaN,350,66,65,48,62,57,52,6,False
Gogoat,673,NaN,531,123,100,62,97,81,68,6,False

In [14]:
pokemon.loc['Grass', 'Attack']

Name
Bulbasaur                 49
Ivysaur                   62
Venusaur                  82
VenusaurMega Venusaur    100
Oddish                    50
                        ...
Chespin                   61
Quilladin                 78
Chesnaught               107
Skiddo                    65
Gogoat                   100
Name: Attack, Length: 70, dtype: int64

In [19]:
pokemon.loc['Fire']

,#,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,
Charmander,4,NaN,309,39,52,43,60,50,65,1,False
Charmeleon,5,NaN,405,58,64,58,80,65,80,1,False
Charizard,6,Flying,534,78,84,78,109,85,100,1,False
CharizardMega Charizard X,6,Dragon,634,78,130,111,130,85,100,1,False
CharizardMega Charizard Y,6,Flying,634,78,104,78,159,115,100,1,False
Vulpix,37,NaN,299,38,41,40,50,65,65,1,False
Ninetales,38,NaN,505,73,76,75,81,100,100,1,False
Growlithe,58,NaN,350,55,70,45,70,50,60,1,False
Arcanine,59,NaN,555,90,110,80,100,80,95,1,False
Ponyta,77,NaN,410,50,85,55,65,65,90,1,False
Rapidash,78,NaN,500,65,100,70,80,80,105,1,False
Magmar,126,NaN,495,65,95,57,100,85,93,1,False
Flareon,136,NaN,525,65,130,60,95,110,65,1,False
Moltres,146,Flying,580,90,100,90,125,85,90,1,True
Cyndaquil,155,NaN,309,39,52,43,60,50,65,2,False
Quilava,156,NaN,405,58,64,58,80,65,80,2,False
Typhlosion,157,NaN,534,78,84,78,109,85,100,2,False
Slugma,218,NaN,250,40,40,40,70,40,20,2,False
Magcargo,219,Rock,410,50,50,120,80,80,30,2,False
Magby,240,NaN,365,45,75,37,70,55,83,2,False
Entei,244,NaN,580,115,115,85,90,75,100,2,True
Ho-oh,250,Flying,680,106,130,90,110,154,90,2,True
Torchic,255,NaN,310,45,60,40,70,50,45,3,False
Combusken,256,Fighting,405,60,85,60,85,60,55,3,False
Blaziken,257,Fighting,530,80,120,70,110,70,80,3,False
BlazikenMega Blaziken,257,Fighting,630,80,160,80,130,80,100,3,False
Numel,322,Ground,305,60,60,40,65,45,35,3,False
Camerupt,323,Ground,460,70,100,70,105,75,40,3,False
CameruptMega Camerupt,323,Ground,560,70,120,100,145,105,20,3,False
Torkoal,324,NaN,470,70,85,140,85,70,20,3,False
Chimchar,390,NaN,309,44,58,44,58,44,61,4,False
Monferno,391,Fighting,405,64,78,52,78,52,81,4,False
Infernape,392,Fighting,534,76,104,71,104,71,108,4,False
Magmortar,467,NaN,540,75,95,67,125,95,83,4,False
Heatran,485,Steel,600,91,90,106,130,106,77,4,True
Tepig,498,NaN,308,65,63,45,45,45,45,5,False
Pignite,499,Fighting,418,90,93,55,70,55,55,5,False
Emboar,500,Fighting,528,110,123,65,100,65,65,5,False
Pansear,513,NaN,316,50,53,48,53,48,64,5,False
Simisear,514,NaN,498,75,98,63,98,63,101,5,False
Darumaka,554,NaN,315,70,90,45,15,45,50,5,False
DarmanitanStandard Mode,555,NaN,480,105,140,55,30,55,95,5,False
DarmanitanZen Mode,555,Psychic,540,105,30,105,140,105,55,5,False
Heatmor,631,NaN,484,85,97,66,105,66,65,5,False
Fennekin,653,NaN,307,40,45,40,62,60,60,6,False
Braixen,654,NaN,409,59,59,58,90,70,73,6,False
Delphox,655,Psychic,534,75,69,72,114,100,104,6,False
Fletchinder,662,Flying,382,62,73,55,56,52,84,6,False
Talonflame,663,Flying,499,78,81,71,74,69,126,6,False
Litleo,667,Normal,369,62,50,58,73,54,72,6,False
Pyroar,668,Normal,507,86,68,72,109,66,106,6,False
Volcanion,721,Water,600,80,110,120,130,90,70,6,True

In [12]:
pokemon.loc[('Grass', 'Bulbasaur')]

#                  1
Type 2        Poison
Total            318
HP                45
Attack            49
Defense           49
Sp. Atk           65
Sp. Def           65
Speed             45
Generation         1
Legendary      False
Name: (Grass, Bulbasaur), dtype: object

In [17]:
pokemon.loc[('Grass', 'Bulbasaur'), 'Attack']

np.int64(49)

In [18]:
pokemon.loc[('Grass', 'Bulbasaur'), ['Defense', 'Attack']]

Defense    49
Attack     49
Name: (Grass, Bulbasaur), dtype: int64

In [23]:
pokemon.loc[(['Grass', 'Fire'], ['Bulbasaur', 'Pansear']), :]

,,#,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,Name,,,,,,,,,,,
Grass,Bulbasaur,1,Poison,318,45,49,49,65,65,45,1,False
Fire,Pansear,513,NaN,316,50,53,48,53,48,64,5,False

In [24]:
pokemon.loc[:, 'Bulbasaur', :]

,#,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,,
Grass,1,Poison,318,45,49,49,65,65,45,1,False

In [25]:
pokemon.loc[(slice(None), 'Bulbasaur'), 'Legendary']

Type 1  Name
Grass   Bulbasaur    False
Name: Legendary, dtype: bool

In [26]:
pokemon.loc[pd.IndexSlice[:, 'Bulbasaur'], 'Legendary']

Type 1  Name
Grass   Bulbasaur    False
Name: Legendary, dtype: bool